"""empty message

Revision ID: 1c2e9ad51e61
Revises: b46a6fafa1b6
Create Date: 2023-10-29 09:42:07.738333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c2e9ad51e61'
down_revision = 'b46a6fafa1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_t', sa.DateTime(), nullable=True))
        batch_op.drop_column('modify_t')

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_t', sa.DateTime(), nullable=True))
        batch_op.drop_column('modify_t')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_t', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('update_t')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_t', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('update_t')

    # ### end Alembic commands ###
