"""empty message

Revision ID: 275daeb552a5
Revises: 1c2e9ad51e61
Create Date: 2023-10-29 10:35:05.506074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '275daeb552a5'
down_revision = '1c2e9ad51e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perm', sa.Integer(), nullable=False))
        batch_op.drop_column('super')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('perm')

    # ### end Alembic commands ###
