"""empty message

Revision ID: 2cd2fe86f3fa
Revises: 296bd4cae995
Create Date: 2023-10-29 04:23:36.420957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd2fe86f3fa'
down_revision = '296bd4cae995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['member_name'], ['member_name'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_name', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['member_name'], ['member_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_name')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
