"""empty message

Revision ID: 35b1274ad3dc
Revises: 1c6cc9df1197
Create Date: 2023-10-28 22:26:13.578010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35b1274ad3dc'
down_revision = '1c6cc9df1197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notice_idx', sa.Integer(), nullable=True))
        batch_op.drop_constraint('notice_comment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'notice', ['notice_idx'], ['idx'], ondelete='CASCADE')
        batch_op.drop_column('board_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_idx', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notice_comment_ibfk_1', 'notice', ['board_idx'], ['idx'], ondelete='CASCADE')
        batch_op.drop_column('notice_idx')

    # ### end Alembic commands ###
