"""empty message

Revision ID: 633610dbaa3c
Revises: f6a1f5fd5837
Create Date: 2023-10-29 08:17:28.385209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633610dbaa3c'
down_revision = 'f6a1f5fd5837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_idx', sa.Integer(), server_default='0', nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_idx'], ['idx'], ondelete='CASCADE')

    with op.batch_alter_table('notice_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_idx', sa.Integer(), server_default='0', nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_idx'], ['idx'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_idx')

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_idx')

    # ### end Alembic commands ###
