"""empty message

Revision ID: 68f2e410dcd4
Revises: fb6d240d6dd7
Create Date: 2023-10-30 01:31:04.318609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68f2e410dcd4'
down_revision = 'fb6d240d6dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notice_idx', sa.Integer(), nullable=False))
        batch_op.drop_constraint('notice_like_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'notice', ['notice_idx'], ['idx'], ondelete='CASCADE')
        batch_op.drop_column('board_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_idx', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notice_like_ibfk_1', 'board', ['board_idx'], ['idx'], ondelete='CASCADE')
        batch_op.drop_column('notice_idx')

    # ### end Alembic commands ###
