"""empty message

Revision ID: 72080b49bef1
Revises: ae50803d8697
Create Date: 2023-10-29 12:40:51.959336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72080b49bef1'
down_revision = 'ae50803d8697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_like',
    sa.Column('user_idx', sa.Integer(), nullable=False),
    sa.Column('board_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_idx'], ['board.idx'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_idx'], ['users.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_idx', 'board_idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_like')
    # ### end Alembic commands ###
