"""empty message

Revision ID: 8e56f2cb2902
Revises: 
Create Date: 2023-10-28 03:49:31.541966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e56f2cb2902'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('write_t', sa.DateTime(), nullable=False),
    sa.Column('file_YN', sa.Boolean(), nullable=False),
    sa.Column('secret_YN', sa.Boolean(), nullable=False),
    sa.Column('posting_password', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('comment',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('board_idx', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('write_t', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_idx'], ['board.idx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('board')
    # ### end Alembic commands ###
