"""empty message

Revision ID: 9e6583e6f8a6
Revises: ce68dc01b9fc
Create Date: 2023-10-29 03:52:30.307068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e6583e6f8a6'
down_revision = 'ce68dc01b9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.alter_column('member_name',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['member_name'], ['member_name'], ondelete='CASCADE')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_name', sa.Integer(), server_default='1', nullable=True))
        batch_op.create_foreign_key(None, 'users', ['member_name'], ['member_name'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_name')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('member_name',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
