"""empty message

Revision ID: ae50803d8697
Revises: 275daeb552a5
Create Date: 2023-10-29 11:19:52.159742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae50803d8697'
down_revision = '275daeb552a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('perm',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('perm',
               existing_type=sa.String(length=1),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
