"""empty message

Revision ID: b46a6fafa1b6
Revises: 7608ebb72d6f
Create Date: 2023-10-29 09:02:46.166235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46a6fafa1b6'
down_revision = '7608ebb72d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_t', sa.DateTime(), nullable=True))

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_t', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_column('modify_t')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('modify_t')

    # ### end Alembic commands ###
