"""empty message

Revision ID: d91e0e2fb7a3
Revises: 9e6583e6f8a6
Create Date: 2023-10-29 04:12:30.717424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd91e0e2fb7a3'
down_revision = '9e6583e6f8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.alter_column('member_name',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['member_name'], ['member_name'], ondelete='CASCADE')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_name', sa.String(length=30), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['member_name'], ['member_name'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_name')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('member_name',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
